plugins/redmine_dmsf/config/routes.rb
# encoding: utf-8
#
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
# Copyright (C) 2012    Daniel Munn <dan.munn@munnster.co.uk>
# Copyright (C) 2011-17 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


if Redmine::Plugin.installed? :redmine_dmsf
  RedmineApp::Application.routes.draw do

    #
    # dmsf controller
    #   /projects/<project>/dmsf
    #   [As this controller also processes 'folders' it maybe better to branch into a folder route rather than leaving it as is]
    ##
    post '/projects/:id/dmsf/create', :controller => 'dmsf', :action => 'create'
    get '/projects/:id/dmsf/notify/activate', :controller => 'dmsf', :action => 'notify_activate', :as => 'notify_activate_dmsf'
    get '/projects/:id/dmsf/notify/deactivate', :controller => 'dmsf', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf'
    delete '/projects/:id/dmsf/delete', :controller => 'dmsf', :action => 'delete', :as => 'delete_dmsf'
    post '/projects/:id/dmsf/save', :controller => 'dmsf', :action => 'save'
    post '/projects/:id/dmsf/save/root', :controller => 'dmsf', :action => 'save_root'
    post '/projects/:id/dmsf/entries', :controller => 'dmsf', :action => 'entries_operation', :as => 'entries_operations_dmsf'
    post '/projects/:id/dmsf/tag_changed', :controller => 'dmsf', :action => 'tag_changed', :as => 'tag_changed'
    post '/projects/:id/dmsf/entries/delete', :controller => 'dmsf', :action => 'delete_entries', :as => 'delete_entries'
    post '/projects/:id/dmsf/entries/email', :to => 'dmsf#entries_email', :as => 'email_entries'
    get '/projects/:id/dmsf/entries/download_email_entries', :controller => 'dmsf', :action => 'download_email_entries', :as => 'download_email_entries'
    get '/projects/:id/dmsf/lock', :controller => 'dmsf', :action => 'lock', :as => 'lock_dmsf'
    get '/projects/:id/dmsf/unlock', :controller => 'dmsf', :action => 'unlock', :as => 'unlock_dmsf'
    get '/projects/:id/dmsf/', :controller => 'dmsf', :action => 'show', :as => 'dmsf_folder'
    get '/projects/:id/dmsf/new', :controller => 'dmsf', :action => 'new', :as => 'new_dmsf'
    get '/projects/:id/dmsf/edit', :controller => 'dmsf', :action => 'edit', :as => 'edit_dmsf'
    get '/projects/:id/dmsf/edit/root', :controller => 'dmsf', :action => 'edit_root', :as => 'edit_root_dmsf'
    get '/projects/:id/dmsf/trash', :controller => 'dmsf', :action => 'trash', :as => 'trash_dmsf'
    get '/projects/:id/dmsf/restore', :controller => 'dmsf', :action => 'restore', :as => 'restore_dmsf'
    post '/projects/:id/dmsf/expand_folder', :controller => 'dmsf', :action => 'expand_folder', :as => 'expand_folder_dmsf'

    #
    # dmsf_state controller
    #   /projects/<project>/dmsf/state
    ##
    post '/projects/:id/dmsf/state', :controller => 'dmsf_state', :action => 'user_pref_save', :as => 'dmsf_user_pref_save'

    #
    #  dmsf_upload controller
    #   /projects/<project>/dmsf/upload - dmsf_upload controller
    ##

    post '/projects/:id/dmsf/upload/files', :controller => 'dmsf_upload', :action => 'upload_files'
    post '/projects/:id/dmsf/upload/file', :controller => 'dmsf_upload', :action => 'upload_file'
    post '/projects/:id/dmsf/upload', :controller => 'dmsf_upload', :action => 'upload'
    post '/projects/:id/dmsf/upload/commit', :controller => 'dmsf_upload', :action => 'commit_files'
    post '/projects/:id/dmsf/commit', :controller => 'dmsf_upload', :action => 'commit'
    match 'dmsf_uploads', :to => 'dmsf_upload#upload', :via => :post
    delete '/dmsf/attachments/:id/delete', :to => 'dmsf_upload#delete_dmsf_attachment', :as => 'dmsf_attachment'
    delete '/dmsf/link_attachments/:id/delete', :to => 'dmsf_upload#delete_dmsf_link_attachment', :as => 'dmsf_link_attachment'

    #
    # dmsf_files controller
    #   /dmsf/files/<file id>
    ##
    get '/dmsf/files/:id/notify/activate', :controller => 'dmsf_files', :action => 'notify_activate', :as => 'notify_activate_dmsf_files'
    get '/dmsf/files/:id/notify/deactivate', :controller => 'dmsf_files', :action => 'notify_deactivate', :as => 'notify_deactivate_dmsf_files'
    get '/dmsf/files/:id/lock', :controller => 'dmsf_files', :action => 'lock', :as => 'lock_dmsf_files'
    get '/dmsf/files/:id/unlock', :controller => 'dmsf_files', :action => 'unlock', :as => 'unlock_dmsf_files'
    post '/dmsf/files/:id/delete', :controller => 'dmsf_files', :action => 'delete', :as => 'delete_dmsf_files'
    post '/dmsf/files/:id/revision/create', :controller => 'dmsf_files', :action => 'create_revision'
    get '/dmsf/files/:id/revision/delete', :controller => 'dmsf_files', :action => 'delete_revision', :as => 'delete_revision'
    get '/dmsf/files/:id/download', :to => 'dmsf_files#view', :download => '', :as => 'download_dmsf_file' # Otherwise will not route nil into the download param
    get '/dmsf/files/:id/view', :to => 'dmsf_files#view', :as => 'view_dmsf_file'
    get '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'show', :as => 'dmsf_file'
    delete '/dmsf/files/:id', :controller => 'dmsf_files', :action => 'delete'
    get '/dmsf/files/:id/restore', :controller => 'dmsf_files', :action => 'restore', :as => 'restore_dmsf_file'
    get '/dmsf/files/:id/thumbnail', :to => 'dmsf_files#thumbnail', :as => 'dmsf_thumbnail'

    #
    # url controller
    #   /dmsf/links/<file id>
    ##
    get '/dmsf/links/:id/restore', :controller => 'dmsf_links', :action => 'restore', :as => 'restore_dmsf_link'
    delete '/dmsf/links/:id', :controller => 'dmsf_links', :action => 'delete'

    # Just to keep backward compatibility with old external direct links
    get '/dmsf_files/:id', :controller => 'dmsf_files', :action => 'show'
    get '/dmsf_files/:id/download', :controller => 'dmsf_files', :action => 'show', :download => ''

    #
    # files_copy controller
    #   /dmsf/files/<file id>/copy
    ##
    post '/dmsf/files/:id/copy/create', :controller => 'dmsf_files_copy', :action => 'create'
    post '/dmsf/files/:id/copy/move', :controller => 'dmsf_files_copy', :action => 'move'
    get '/dmsf/files/:id/copy', :controller => 'dmsf_files_copy', :action => 'new', :as => 'copy_file'

    #
    # folders_copy controller
    #   /dmsf/folders/<folder id>/copy
    ##
    #verify :method => :post, :only => [:copy_to], :render => { :nothing => true, :status => :method_not_allowed }
    post '/dmsf/folders/:id/copy/to', :controller => 'dmsf_folders_copy', :action => 'copy_to'
    get '/dmsf/folders/:id/copy', :controller => 'dmsf_folders_copy', :action => 'new', :as => 'copy_folder'

    #
    # DAV4Rack implementation of Webdav
    dav_engine = DAV4Rack::Handler.new(
      :root_uri_path => "#{Redmine::Utils::relative_url_root}/dmsf/webdav",
      :resource_class => RedmineDmsf::Webdav::ResourceProxy,
      :controller_class => RedmineDmsf::Webdav::Controller,
      :log_to => Rails.logger
    )
    mount dav_engine, :at => '/dmsf/webdav'
    mount dav_engine, :at => '/', :via => :options
    mount dav_engine, :at => '/', :via => :propfind
    mount dav_engine, :at => '/dmsf', :via => :propfind

    # Approval workflow
    resources :dmsf_workflows do
      member do
        get 'autocomplete_for_user'
        get 'action'
        get 'assign'
        get 'log'
        post 'new_action'
        get 'start'
        post 'assignment'
        get 'new_step'
        put 'update_step'
        delete 'delete_step'
      end
    end

    match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'add_step', :id => /\d+/, :via => :post
    match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'remove_step', :id => /\d+/, :via => :delete
    match 'dmsf_workflows/:id/edit', :controller => 'dmsf_workflows', :action => 'reorder_steps', :id => /\d+/, :via => :put

    # Links
    resources :dmsf_links do
      member do
        get 'restore'
        get 'autocomplete_for_project'
        get 'autocomplete_for_folder'
      end
    end

    # Public URLs
    resource :dmsf_public_urls

     # Folder permissions
    resource :dmsf_folder_permissions do
      member do
        get 'autocomplete_for_user'
        post 'append'
      end
    end

  end
end

plugins/redmine_dmsf/app/helpers/dmsf_upload_helper.rb
# encoding: utf-8
# 
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-17 Karel Pičman <karel.picman@lbcfree.net>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module DmsfUploadHelper
  include Redmine::I18n

  def self.commit_files_internal(commited_files, project, folder, controller)
    failed_uploads = []
    files = []
    if commited_files && commited_files.is_a?(Hash)
      failed_uploads = []
      commited_files.each_value do |commited_file|
        name = commited_file[:name]
        new_revision = DmsfFileRevision.new
        file = DmsfFile.visible.find_file_by_name(project, folder, name)
        unless file
          link = DmsfLink.find_link_by_file_name(project, folder, name)
          file = link.target_file if link
        end

        unless file
          file = DmsfFile.new
          file.project_id = project.id
          file.name = name
          file.dmsf_folder = folder
          file.notification = Setting.plugin_redmine_dmsf['dmsf_default_notifications'].present?
          new_revision.minor_version = 0
          new_revision.major_version = 0
        else
          if file.last_revision
            last_revision = file.last_revision
            new_revision.source_revision = last_revision
            new_revision.major_version = last_revision.major_version
            new_revision.minor_version = last_revision.minor_version
          else
            new_revision.minor_version = 0
            new_revision.major_version = 0
          end
        end

        if file.locked_for_user?
          failed_uploads.push(commited_file)
          next
        end

        new_revision.dmsf_file = file
        new_revision.user = User.current
        new_revision.name = name
        new_revision.title = commited_file[:title]
        new_revision.description = commited_file[:description]
        new_revision.comment = commited_file[:comment]
        version = commited_file[:version].to_i
        if version == 3
          new_revision.major_version = commited_file[:custom_version_major].to_i
          new_revision.minor_version = commited_file[:custom_version_minor].to_i
        else
          new_revision.increase_version(version)
        end
        new_revision.mime_type = commited_file[:mime_type]
        new_revision.size = commited_file[:size]
        new_revision.digest = DmsfFileRevision.create_digest commited_file[:tempfile_path]

        if commited_file[:custom_field_values].present?
          commited_file[:custom_field_values].each_with_index do |v, i|
            new_revision.custom_field_values[i].value = v[1]
          end
        end

        # Need to save file first to generate id for it in case of creation.
        # File id is needed to properly generate revision disk filename
        if new_revision.valid? && file.save
          new_revision.disk_filename = new_revision.new_storage_filename
        else
          Rails.logger.error (new_revision.errors.full_messages + file.errors.full_messages).to_sentence
          failed_uploads.push(commited_file)
          next
        end

        if new_revision.save
          new_revision.assign_workflow(commited_file[:dmsf_workflow_id])
          begin
            FileUtils.mv commited_file[:tempfile_path], new_revision.disk_file(false)
            FileUtils.chmod 'u=wr,g=r', new_revision.disk_file(false)
            file.set_last_revision new_revision
            files.push(file)
            if file.container.is_a?(Issue)
              file.container.dmsf_file_added(file)
            end
          rescue Exception => e
            Rails.logger.error e.message
            controller.flash[:error] = e.message
            failed_uploads.push(file)
          end
        else
          failed_uploads.push(commited_file)
        end
        # Approval workflow
        if commited_file[:workflow_id].present?
          wf = DmsfWorkflow.find_by_id commited_file[:workflow_id]
          if wf
            # Assign the workflow
            new_revision.set_workflow(wf.id, 'assign')
            new_revision.assign_workflow(wf.id)
            # Start the workflow
            new_revision.set_workflow(wf.id, 'start')
            if new_revision.save
              wf.notify_users(project, new_revision, controller)
              begin
                file.lock!
              rescue DmsfLockError => e
                Rails.logger.warn e.message
              end
            else
              Rails.logger.error l(:error_workflow_assign)
            end
          end
        end
      end
      # Notifications
      if ((folder && folder.notification?) || (!folder && project.dmsf_notification?))
        begin
          recipients = DmsfMailer.get_notify_users(project, files)
          recipients.each do |u|
            DmsfMailer.files_updated(u, project, files).deliver
          end
          if Setting.plugin_redmine_dmsf['dmsf_display_notified_recipients'] == '1'
            unless recipients.empty?
              to = recipients.collect{ |r| r.name }.first(DMSF_MAX_NOTIFICATION_RECEIVERS_INFO).join(', ')
              to << ((recipients.count > DMSF_MAX_NOTIFICATION_RECEIVERS_INFO) ? ',...' : '.')
              controller.flash[:warning] = l(:warning_email_notifications, :to => to)
            end
          end
        rescue Exception => e
          Rails.logger.error "Could not send email notifications: #{e.message}"
        end
      end
    end
    if failed_uploads.present?
      controller.flash[:warning] = l(:warning_some_files_were_not_commited, :files => failed_uploads.map{|u| u['name']}.join(', '))
    end
    [files, failed_uploads]
  end

end

plugins/redmine_dmsf/app/views/dmsf_upload/_form.html.erb
<%
  # encoding: utf-8
  #
  # Redmine plugin for Document Management System "Features"
  #
  # Copyright (C) 2011-17 Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<span id="dmsf_attachments_fields">
  <% if defined?(container) && container && container.saved_dmsf_attachments.present? %>
    <% container.saved_dmsf_attachments.each_with_index do |attachment, i| %>
      <span id="dmsf_attachments_p<%= i %>", class="attachment">
          <%= hidden_field_tag "dmsf_attachments[p#{i}][token]", "#{attachment.token}" %>
          <%= text_field_tag("dmsf_attachments[p#{i}][filename]", attachment.filename, :class => 'filename') %>
          <%= text_field_tag("dmsf_attachments[p#{i}][description]", attachment.description, :maxlength => 255,
              :placeholder => l(:label_optional_description), :class => 'description') if description %>
          <%= link_to('', dmsf_attachment_path(attachment, :attachment_id => "p#{i}", :format => 'js'),
                :method => 'delete', :remote => true, :class => 'remove-upload icon-only icon-del') %>
          <% wf = container.saved_dmsf_attachments_wfs[attachment.id] %>
          <% if wf %>
              <a href="javascript:void(0);" title="<%= l(:title_assigned) %>" class="icon-only icon-wf-assigned"></a>
              <%= hidden_field_tag("dmsf_attachments_wfs[p#{i}]", wf.id) if wf %>
          <% else %>
              <%= link_to('',  assign_dmsf_workflow_path(:id => container.project.id, :project_id => container.project.id,
                :attachment_id => i + 1), :title => l(:label_dmsf_wokflow_action_assign),
                :remote => true, :class => 'modify-upload icon-only icon-wf-none') %>
          <% end %>
      </span>
    <% end %>
  <% end %>
</span>

<span id="dmsf_links_attachments_fields">
<% if defined?(container) && container && container.saved_dmsf_links.present? %>
    <% container.saved_dmsf_links.each_with_index do |dmsf_link, index| %>
        <span id="dmsf_links_attachments_<%= index %>", class="attachment">
          <input name="dmsf_links[<%= index %>]" value="<%= dmsf_link.id %>" type="hidden">
          <input type="text" class='filename readonly' value="<%= dmsf_link.name %>">
           <%= link_to('', dmsf_link_attachment_path(dmsf_link, :link_id => "#{index}", :format => 'js'),
                      :method => 'delete', :remote => true, :class => 'remove-upload icon-only icon-del') %>
            <% wf = container.saved_dmsf_links_wfs[dmsf_link.id] %>
            <% if wf %>
              <a href="javascript:void(0);" title="<%= l(:title_assigned) %>" class="modify-upload icon-only icon-wf-assigned"></a>
                <%= hidden_field_tag("dmsf_links_wfs[#{dmsf_link.id}]", wf.id) if wf %>
            <% else %>
              <%= render(:partial => 'dmsf_workflows/approval_workflow_button',
                 :locals => {:file => dmsf_link.target_file,
                             :file_approval_allowed => User.current.allowed_to?(:file_approval, dmsf_link.target_file.project),
                             :workflows_available => DmsfWorkflow.where(
                                 ['project_id = ? OR project_id IS NULL', dmsf_link.target_file.project_id]).exists?,
                             :project => dmsf_link.target_file.project, :wf => wf, :dmsf_link_id => dmsf_link.id }) %>
            <% end %>
        </span>
    <% end %>
<% end %>
</span>

<span class="dmsf_add_attachment add_attachment">
  <%= file_field_tag 'dmsf_attachments[dummy][file]',
                   :id => nil,
                   :class => 'file_selector',
                   :multiple => multiple,
                   :onchange => "dmsfAddInputFiles(this);",
                   :data => {
                       :max_file_size => Setting.attachment_max_size.to_i.kilobytes,
                       :max_file_size_message => l(:error_attachment_too_big,
                       :max_size => number_to_human_size(Setting.attachment_max_size.to_i.kilobytes)),
                       :max_concurrent_uploads => Redmine::Configuration['max_concurrent_ajax_uploads'].to_i,
                       :upload_path => dmsf_uploads_path(:format => 'js'),
                       :description_placeholder => l(:label_optional_description),
                       :project => "#{@project.identifier}",
                       :description => description,
                       :awf => awf
                   } %>
</span>
<% if defined?(container) && container %>
    <span class="dmsf_add_link">
        <%= link_to l(:label_link_from),
                    new_dmsf_link_path(:project_id => container.project.id, :type => 'link_from', :container => container.class.name),
                    :title => l(:title_create_link), :class => 'icon icon-add file_selector', :remote => true %>
      </span>
<% end %>
<span class="info">
    (<%= l(:label_max_size) %>: <%= number_to_human_size(Setting.attachment_max_size.to_i.kilobytes) %>)
</span>

plugins/redmine_dmsf/app/views/dmsf_upload/_upload_file.html.erb
<%
  # encoding: utf-8
  #
  # Redmine plugin for Document Management System "Features"
  #
  # Copyright (C) 2011    Vít Jonáš <vit.jonas@gmail.com>
  # Copyright (C) 2012    Daniel Munn <dan.munn@munnster.co.uk>
  # Copyright (C) 2011-17 Karel Pičman <karel.picman@kontron.com>
  #
  # This program is free software; you can redistribute it and/or
  # modify it under the terms of the GNU General Public License
  # as published by the Free Software Foundation; either version 2
  # of the License, or (at your option) any later version.
  #
  # This program is distributed in the hope that it will be useful,
  # but WITHOUT ANY WARRANTY; without even the implied warranty of
  # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  # GNU General Public License for more details.
  #
  # You should have received a copy of the GNU General Public License
  # along with this program; if not, write to the Free Software
  # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

<div class="box tabular" style="padding-top: 10px">
  <%= hidden_field_tag("commited_files[#{i}][disk_filename]", upload.disk_filename) %>
  <%= hidden_field_tag("commited_files[#{i}][tempfile_path]", upload.tempfile_path) %>
  <%= hidden_field_tag("commited_files[#{i}][size]", upload.size) %>
  <%= hidden_field_tag("commited_files[#{i}][mime_type]", upload.mime_type) %>
  <div class="clear">
    <div class="splitcontentleft">
      <p>
        <%= label_tag("commited_files[#{i}][title]", l(:label_title)) %>
        <%= text_field_tag("commited_files[#{i}][title]", upload.title, :required => true) %>
      </p>
    </div>
    <div class="splitcontentright">
      <p>
        <%= label_tag('', l(:label_filename)) %>
        <%= text_field_tag(:name, h(upload.name), :readonly => true) %>
        <%= hidden_field_tag("commited_files[#{i}][name]", upload.name) %>
      </p>
    </div>
  </div>
  <p>
    <%= label_tag("commited_files[#{i}][description]", l(:label_description)) %>
    <%= text_area_tag("commited_files[#{i}][description]", upload.description, :rows => 6, :class => 'wiki-edit') %>
  </p>
  <div class="clear">
    <div class="splitcontentright">
      <div class="custom_fields">
        <% upload.custom_values.each do |value| %>
            <% value.value = nil if value.custom_field.dmsf_not_inheritable %>
            <p><%= custom_field_tag_with_label "commited_files[#{i}]", value %></p>
        <% end %>
      </div>
    </div>
    <div class="splitcontentleft">
      <p>
        <%= label_tag("commited_files[#{i}][version]_minor", l(:label_dmsf_version)) %>
        <%= radio_button_tag("commited_files[#{i}][version]", 1, true) %>
        <%= upload.major_version %>.<%= upload.minor_version + 1 %>
        <%= l(:option_version_minor) %><br/>
        <%= radio_button_tag("commited_files[#{i}][version]", 2) %>
        <%= upload.major_version + 1 %>.0
        <%= l(:option_version_major) %><br/>
        <%= radio_button_tag("commited_files[#{i}][version]", 3) %>
        <%= select_tag "commited_files[#{i}][custom_version_major]",
                       options_for_select(0..99, upload.major_version + 2),
                       :onchange => "$('#commited_files_#{i}_version_3').prop('checked', true)",
                       :class => 'dmsf_select_version'%>.
        <%= select_tag "commited_files[#{i}][custom_version_minor]",
                       options_for_select(0..99, upload.minor_version + 1),
                       :onchange => "$('#commited_files_#{i}_version_3').prop('checked', true)",
                       :class => 'dmsf_select_version' %>
        <%= l(:option_version_custom) %>
      </p>
    </div>
    <div class="splitcontentright">
      <p>
        <%= label_tag '', l(:label_mime) %>
        <%= text_field_tag(:name, h(upload.mime_type), :readonly => true) %>
      </p>
      <p>
        <%= label_tag('', l(:label_size)) %>
        <%= text_field_tag(:name, number_to_human_size(upload.size), :readonly => true) %>
      </p>
    </div>
  </div>
  <p>
    <%= label_tag("commited_files[#{i}][comment]", l(:label_comment)) %>
    <%= text_area_tag("commited_files[#{i}][comment]", upload.comment, :rows => 2, :class => 'wiki-edit') %>
  </p>
</div>

<%= wikitoolbar_for "commited_files_#{i}_description" %>

plugins/redmine_dmsf/app/views/dmsf_upload/delete_dmsf_attachment.js.erb
$('#dmsf_attachments_<%= j params[:attachment_id] %>').remove();

plugins/redmine_dmsf/app/views/dmsf_upload/delete_dmsf_link_attachment.js.erb
$('#dmsf_links_attachments_<%= j params[:link_id] %>').remove();

plugins/redmine_dmsf/app/views/dmsf_upload/upload.js.erb
<%
# encoding: utf-8
#
# Redmine plugin for Document Management System "Features"
#
# Copyright (C) 2011-17 Karel Pičman <karel.picman@kontron.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%>

var fileSpan = $('#dmsf_attachments_<%= j params[:attachment_id] %>');
<% if @attachment.new_record? %>
  fileSpan.hide();
  alert("<%= escape_javascript @attachment.errors.full_messages.join(', ') %>");
<% else %>
$('<input>', { type: 'hidden', name: 'dmsf_attachments[<%= j params[:attachment_id] %>][token]' } ).val('<%= j @attachment.token %>').appendTo(fileSpan);
fileSpan.find('a.dmsf-remove-upload')
  .attr({
    "data-remote": true,
    "data-method": 'delete',
    href: '<%= j dmsf_attachment_path(@attachment, :attachment_id => params[:attachment_id], :format => 'js') %>'
  })
  .off('click');
<% end %>